name: trabajo2
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Version info
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  provider: ^6.0.5
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/perro.jpg
    - assets/audio/select.mp3
    - assets/audio/deselect.mp3
    - assets/audio/correct.mp3
